[RDG-41] create player mechanics
MatthijsLuijten/RL-dodge-game pull request #6
Opened 2024-02-18 17:02 UTC by DaphneSmits

## Describe your changes

I have created the `Agent` class and its subclass `Player`. The `Agent` class represents the common functionality of all possible agents inside the game (i.e. the `Player` and all `Enemy` instances). This way we can reuse functions that both will use, such as `move()`, `render()` and `reset()`. 

I have moved the main player functionality from `environment.py` to the new `Player` class. Functionally nothing changed, but this restructuring makes it easier to generalize and add new agents to the game.  

## List of tests added

Not yet, but will look into it.

## Checklist before requesting a review
- [x] PR title contains ticket ID
- [ ] If it is a core feature, I have added thorough tests.
- [x] I have included documentation

2024-02-19 10:10 UTC, MatthijsLuijten requested changes
Great work, overall looks really good. Some minor comments and suggestions <3.
I didn't have the opportunity to load the PR in vscode, just checked it in browser, so I will have to do that yet!

2024-02-19 10:10 UTC, MatthijsLuijten commented on tests/test_player.py
> +        self.assertEqual(self.player.location, (101, 100))
@DaphneSmits Can you add some small docstring (can be a one-liner) what this function tests? Or do you think this is not needed and the function names say enough?

2024-02-19 10:10 UTC, MatthijsLuijten commented on src/agent.py
> +            pygame.Rect: the created circle.
`pygame.Rect` --> Should this be a circle?

2024-02-19 10:10 UTC, MatthijsLuijten commented on src/agent.py
> +        """Move the agent by a specified amount.
Maybe something like: `Move the agent given a direction.`

2024-02-19 10:10 UTC, MatthijsLuijten commented on src/player.py
> +        return super().render(screen)
Do we have to specify this function here if it calls the `super()` function? I am not sure about this, but maybe we can just leave the whole `def render()` function out of the class? I think we only want to specify this function if we want a different behavior then specified in the parent class.

2024-02-19 10:10 UTC, MatthijsLuijten commented on src/player.py
> +        super().move(move)
Same as above

2024-02-19 10:10 UTC, MatthijsLuijten commented on src/environment.py
> +        self, screen: Surface, player_size: int = 10, render_on: bool = False
In `main.py`, should line 12 (`env = Environment(screen=screen, render_on=True)`) be updated with the player size as well?

2024-02-20 17:13 UTC, DaphneSmits reviewed
Thanks for the review! I have addressed the comments and/or left you a comment about them

2024-02-20 17:13 UTC, DaphneSmits commented on src/agent.py
> +            pygame.Rect: the created circle.
I looked it up and it actually returns the bounding rectangle: https://www.pygame.org/docs/ref/draw.html#pygame.draw.circle:~:text=the%20entire%20circle.-,Returns,will%20be%20truncated)%20and%20its%20width%20and%20height%20will%20be%200,-Return%20type

2024-02-20 17:13 UTC, DaphneSmits commented on src/environment.py
> +        self, screen: Surface, player_size: int = 10, render_on: bool = False
I think that is only necessary if we do not want to use the default value. I would say for now that is fine? Wdyt?

2024-02-20 17:13 UTC, DaphneSmits commented on src/player.py
> +        return super().render(screen)
Good point! I have deleted them and that works just fine! :smile:

2024-02-22 19:46 UTC, MatthijsLuijten approved these changes
Nice work!

2024-02-22 19:46 UTC, merged